
import React from 'react';
import { 
  TbHome, TbMap, TbRobot, TbMail, TbArrowLeft, TbArrowRight, TbX, 
  TbChevronLeft, TbChevronRight, TbChevronUp, TbChevronDown, TbArrowUp, TbArrowDown, TbPlus, TbMinus, TbDownload, TbExternalLink,
  TbNetwork, TbPhoto, TbClock, TbPlayerPlay, TbCircleCheck,
  TbNews, TbTrendingUp, TbHeart, TbBolt, TbActivity, TbTools, TbBriefcase,
  TbSchool, TbWorld, TbAward, TbBuildingSkyscraper, TbShieldLock,
  TbDeviceGamepad2, TbCpu, TbMotorbike, TbServer, TbCode, TbDeviceMobile,
  TbSkull, TbTrophy, TbWifi, TbVideo, TbFileText, TbShoppingBag, TbChartBar,
  TbLink, TbCamera, TbPlane, TbBook, TbDeviceDesktop, TbBrandYoutube, TbBrandInstagram, TbBrandReddit,
  TbBrandLinkedin, TbBrandGithub, TbBrandX, TbBug, TbDatabase, TbRocket, TbHelp,
  TbBrandWindows, TbBrandXbox, TbBrandTiktok, TbSitemap, TbFaceId,
  TbUser, TbLock, TbKey, TbUsers, TbBrandDiscord, TbBrandTelegram, TbPin, TbAlertTriangle,
  TbLoader, TbSend, TbCopy, TbGhost, TbShoppingCart, TbShieldExclamation, TbGift,
  TbBold, TbItalic, TbList, TbCheckbox, TbGridDots, TbSearch, TbCalculator, TbBulb, TbSparkles, TbRefresh, TbInfoCircle,
  TbTarget, TbEye, TbEyeOff, TbBookmark, TbRadar, TbTerminal, TbBell, TbHistory, TbFilter, TbMenu2, TbDots,
  TbHash, TbFolder, TbDeviceFloppy, TbChartPie, TbCircleX, TbLogout, TbLogin, TbMessageCircle, TbBuildingMosque,
  TbCurrencyBitcoin, TbCurrencyEthereum, TbCurrencyMonero, TbCoin, TbWallet, TbStar,
  TbShare, TbBrandAdobe, TbBrandOpenai, TbMagnet, TbSettings, TbAdjustments,
  TbEdit, TbPencil, TbUpload, TbCloudUpload, TbCrown, TbShieldCheck
} from 'react-icons/tb';

import {
  SiAutodesk, SiBlender, SiSketchup, SiUnrealengine, SiUnity,
  SiPython, SiReact, SiPhp, SiLinux, SiAndroid, SiPlaystation,
  SiSteam, SiGodotengine,
  SiLaravel, SiFlutter, SiDart, SiMysql, SiHackthebox, SiKalilinux, SiWireshark,
  SiMetasploit, SiNotion, SiShopify, SiGoogleanalytics,
  SiLangchain, SiHuggingface, SiYcombinator, SiUdemy, SiPortswigger,
  SiTryhackme, SiCisco, SiKick, SiN8N, SiWoocommerce, SiZapier, SiImdb
} from 'react-icons/si';

import { FaLandmark } from 'react-icons/fa6';
import { BsGpuCard } from 'react-icons/bs';

interface IconProps {
  name: string;
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}

const ICON_MAP: Record<string, React.ElementType> = {
  Share: TbShare,
  Share2: TbShare,
  Home: TbHome,
  Map: TbMap,
  Bot: TbRobot,
  Mail: TbMail,
  ArrowLeft: TbArrowLeft,
  ArrowRight: TbArrowRight,
  ArrowUp: TbArrowUp,
  ArrowDown: TbArrowDown,
  X: TbX,
  ChevronLeft: TbChevronLeft,
  ChevronRight: TbChevronRight,
  ChevronUp: TbChevronUp,
  ChevronDown: TbChevronDown,
  Plus: TbPlus,
  Minus: TbMinus,
  Download: TbDownload,
  Upload: TbUpload,
  UploadCloud: TbCloudUpload,
  Edit: TbEdit,
  Edit2: TbPencil,
  Edit3: TbEdit,
  Pencil: TbPencil,
  Crown: TbCrown,
  ExternalLink: TbExternalLink,
  Info: TbInfoCircle,
  Network: TbNetwork,
  Image: TbPhoto,
  Images: TbPhoto,
  Clock: TbClock,
  Play: TbPlayerPlay,
  CheckCircle: TbCircleCheck,
  CheckCircle2: TbCircleCheck,
  Newspaper: TbNews,
  TrendingUp: TbTrendingUp,
  Heart: TbHeart,
  Zap: TbBolt,
  Activity: TbActivity,
  Tools: TbTools,
  Wrench: TbTools,
  Briefcase: TbBriefcase,
  GraduationCap: TbSchool,
  Globe: TbWorld,
  Award: TbAward,
  Check: TbCircleCheck,
  HelpCircle: TbHelp,
  Video: TbVideo,
  FileText: TbFileText,
  ShoppingBag: TbShoppingBag,
  ShoppingCart: TbShoppingCart,
  BarChart: TbChartBar,
  Link: TbLink,
  Camera: TbCamera,
  Plane: TbPlane,
  Landmark: FaLandmark,
  PenTool: TbTools,
  BookOpen: TbBook,
  Monitor: TbDeviceDesktop,
  Youtube: TbBrandYoutube,
  Imdb: SiImdb,
  IMDB: SiImdb,
  imdb: SiImdb,
  Reddit: TbBrandReddit,
  BrandReddit: TbBrandReddit,
  Instagram: TbBrandInstagram,
  Linkedin: TbBrandLinkedin,
  Github: TbBrandGithub,
  Twitter: TbBrandX,
  Tiktok: TbBrandTiktok,
  Kick: SiKick,
  FaceId: TbFaceId,
  User: TbUser,
  Wolf: ({ size = 24, className = "" }) => <img src="/images/logo01.png" alt="Logo" width={size} height={size} className={`object-contain ${className}`} />,
  Lock: TbLock,
  Logout: TbLogout,
  Login: TbLogin,
  LogIn: TbLogin,
  Key: TbKey,
  Server: TbServer,
  Code: TbCode,
  Smartphone: TbDeviceMobile,
  Skull: TbSkull,
  Trophy: TbTrophy,
  Wifi: TbWifi,
  Bug: TbBug,
  Database: TbDatabase,
  Rocket: TbRocket,
  Code2: TbCode,
  ShieldCheck: TbShieldLock,
  Building: TbBuildingSkyscraper,
  Shield: TbShieldLock,
  Gamepad: TbDeviceGamepad2,
  Gamepad2: TbDeviceGamepad2,
  Cpu: TbCpu,
  Bike: TbMotorbike,
  Users: TbUsers,
  Discord: TbBrandDiscord,
  Telegram: TbBrandTelegram,
  Pin: TbPin,
  AlertTriangle: TbAlertTriangle,
  ShieldAlert: TbShieldExclamation,
  Loader: TbLoader,
  Loader2: TbLoader,
  Send: TbSend,
  Copy: TbCopy,
  Ghost: TbGhost,
  Gift: TbGift,
  XCircle: TbCircleX,
  AlertOctagon: TbShieldExclamation,
  Sparkles: TbSparkles,
  HardHat: TbTools,
  
  // Hardware Aliases for System Requirements
  RAM: TbCpu,
  CPU: TbCpu,
  GPU: BsGpuCard,
  OS: TbBrandWindows,
  Windows: TbBrandWindows,
  Storage: TbDatabase,
  HDD: TbDatabase,
  SSD: TbDatabase,
  Memory: TbCpu,
  DirectX: TbBolt,

  BrandAutoCAD: SiAutodesk,
  BrandRevit: SiAutodesk,
  BrandRhino: SiAutodesk,
  BrandBlender: SiBlender,
  BrandSketchUp: SiSketchup,
  BrandLumion: TbPhoto,
  BrandTwinmotion: TbPhoto,
  BrandVRay: TbPhoto,
  BrandUnreal: SiUnrealengine,
  BrandD5: TbPhoto,
  BrandAdobe: TbBrandAdobe,
  BrandUnity: SiUnity,
  BrandPython: SiPython,
  BrandReact: SiReact,
  BrandGoPro: TbCamera,
  BrandPHP: SiPhp,
  BrandCEH: SiHackthebox,
  BrandDart: SiDart,
  BrandFlutter: SiFlutter,
  BrandLaravel: SiLaravel,
  BrandMySQL: SiMysql,
  BrandLinux: SiLinux,
  BrandWindows: TbBrandWindows,
  BrandAndroid: SiAndroid,
  BrandRuby: TbCode,
  BrandPlaystation: SiPlaystation,
  BrandXbox: TbBrandXbox,
  BrandSteam: SiSteam,
  BrandGodot: SiGodotengine,
  BrandMaya: SiAutodesk,
  BrandVSCode: TbCode,
  BrandArchiCAD: TbBuildingSkyscraper,
  Brand3dsMax: SiAutodesk,
  Kali: SiKalilinux,
  Wireshark: SiWireshark,
  Metasploit: SiMetasploit,
  Lightroom: TbPhoto,
  Notion: SiNotion,
  Shopify: SiShopify,
  GoogleAnalytics: SiGoogleanalytics,
  OpenAI: TbBrandOpenai,
  LangChain: SiLangchain,
  HuggingFace: SiHuggingface,
  YCombinator: SiYcombinator,
  Udemy: SiUdemy,
  PortSwigger: SiPortswigger,
  TryHackMe: SiTryhackme,
  Cisco: SiCisco,
  BrandN8N: SiN8N,
  BrandWooCommerce: SiWoocommerce,
  BrandZapier: SiZapier,
  Aperture: TbCamera,
  Box: TbCode, 
  Orbit: TbWorld,
  Workflow: TbSitemap,
  Bold: TbBold,
  Italic: TbItalic,
  List: TbList,
  CheckSquare: TbCheckbox,
  Grid: TbGridDots,
  Search: TbSearch,
  Calculator: TbCalculator,
  Bulb: TbBulb,
  RefreshCw: TbRefresh,
  Target: TbTarget,
  Eye: TbEye,
  EyeOff: TbEyeOff,
  Bookmark: TbBookmark,
  Radar: TbRadar,
  Terminal: TbTerminal,
  Bell: TbBell,
  History: TbHistory,
  Filter: TbFilter,
  MoreHorizontal: TbDots,
  Menu: TbMenu2,
  Hash: TbHash,
  Folder: TbFolder,
  Save: TbDeviceFloppy,
  PieChart: TbChartPie,
  MessageSquare: TbMessageCircle,
  BuildingMosque: TbBuildingMosque,
  CurrencyBitcoin: TbCurrencyBitcoin,
  CurrencyEthereum: TbCurrencyEthereum,
  CurrencyMonero: TbCurrencyMonero,
  Coin: TbCoin,
  Wallet: TbWallet,
  Star: TbStar,
  Magnet: TbMagnet,
  Settings: TbSettings,
  Settings2: TbAdjustments,
  Gear: TbSettings,
};

const Icon: React.FC<IconProps> = ({ name, size = 24, className, style }) => {
  if (!name) return <TbHelp size={size} className={className} style={style} />;
  const IconComponent = ICON_MAP[name] || ICON_MAP[name.toUpperCase()] || TbHelp;
  return <IconComponent size={size} className={className} style={style} />;
};

export default Icon;
